"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

# in short
# t = s + _, where "_" is a random char
# every char is actually a encoding, can i convert t and s to ascii, compare sum(t) and sun(s)
# then i can have the "_" 

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_sum = sum([ord(char) for char in s])
        t_sun = sum([ord(char) for char in t])

        return chr(t_sun - s_sum)

# Runtime 35 ms Beats 90.81% of users with Python3